# Generated by Django 5.0.3 on 2024-03-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicos',
        ),
    ]
