# Generated by Django 5.0.3 on 2024-03-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
